#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap.php';

// Prepare the DB
with(new CategoryMigrator)->up();
with(new ClusterMigrator)->up();

// Seed the database with some data
// ...

// Set up a custom inspector for our models
class TreeNodeInspector extends \Boris\ColoredInspector {
  public function objectVars($value) {
    if ( $value instanceof Tree\Node )
      return array_merge($value->getAttributes(), get_object_vars($value));

    return parent::objectVars($value);
  }
}

// Start-up boris REPL and import any defined var (in scope) which happens to be
// a Tree\Node instance into the context
$boris = new \Boris\Boris('> ');

$boris->setInspector(new TreeNodeInspector);

$boris->setLocal(array_filter(get_defined_vars(), function($var) {
  return $var instanceof Tree\Node; }));

$boris->start();
